---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffee-shop.fullname" . }}-secrets
  labels:
    {{- include "coffee-shop.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.postgresql.postgresPassword "" }}
  POSTGRES_PASSWORD: {{ default (randAlphaNum 19 | nospace) .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- else if .Release.IsUpgrade}}
  POSTGRES_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace (print ( include "coffee-shop.fullname" .) "-secrets" )).data "POSTGRES_PASSWORD" }}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- end }}
  API_KEY_TOKEN: {{ .Values.app_config.api_key_token | b64enc | quote }}
