# Stage 1: Build Stage
FROM node:16.14.0 as frontbuild
WORKDIR /app
ENV NODE_ENV='production'
COPY . .
RUN chmod +x start
RUN bash start

# Stage 2: Prod Stage
FROM nginx:1.25.3-alpine-slim
COPY --from=frontbuild /app/dist /usr/share/nginx/html