version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    container_name: backend-db-dev
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.local
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-dev-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coffee_dev"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend-dev:
    env_file:
      - ./backend/.env.local
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-dev-net

  frontend-dev:
    env_file:
      - ./frontend/.env.local
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend-dev
    networks:
      - backend-dev-net

volumes:
  db-data:

networks:
  backend-dev-net: